modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory (24 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="gobber2" #mandatory
version="2.2.69" #mandatory
displayName="Gobber 2" #mandatory
description='''
Gobber into 1.15, a new beginning!
'''


[[dependencies.gobber2]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.gobber2]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
